version: '3'

services:
 database:
    image: bitnami/postgresql
    ports: 
      - '5432:5432'
    container_name: Search-healthy
    restart: always
    volumes: 
      - Search-healthy-disk:/var/lib/postgresql/data
    environment: 
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: Searchhealthy
volumes: 
  Search-healthy-disk: